server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/colegios_bogota
    username: nicolas
    password: nicolas
    driver-class-name: org.postgresql.Driver
  application:
      name: colbog

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
